### ISSUE TITLE
Add optional point count panel (with ebird range map background) to block-n-map

### ISSUE THREAD

**Issue by nmanich** [ngwalton/wbba_tools#14]
I don't think this needs the same concept of shaded blocks, I think you could just throw the points on here as occurring and we'll be fine - guess we can see how that looks.

Alternately, we adopt the block-n-format and instead of how many occurrences over the course of the years, we could add up the number of individuals in a block during that point count day.

**Comment by ngwalton** [comment]
Partly addressed in commit 3bcc5300604d915c74ba2c6b990a28728c22e822. Point count panel is currently not optional and formatting needs work. Currently uses `tm_arrange` to combine faceted block maps with point count map. Should experiment with using dummy levels in block and point count data to integrate point count data with block data in `tm_facets` and remove `tm_arrange`.
