### ISSUE TITLE
NC breeding code

### ISSUE THREAD

**Issue by nmanich** [ngwalton/wbba_tools#18]
Modify all scripts to take the NC as a breeding code and make it no code - i.e. blank or NA.

**Comment by nmanich** [comment]
I fixed data validation via
# Make any NC (No Code) Breeding Codes Blank
ebird_file[ebird_file == "NC" ] <- ""

**Comment by ngwalton** [comment]
Addressed for all files using breeding code in commit e8232237603c033934376cb62c64db67c3f5e83d. NC is currently treated the same as O, F, and the empty string.

**Comment by nmanich** [comment]
Good work!
    On Thursday, August 19, 2021, 02:22:33 PM CDT, Nicholas Walton ***@***.***> wrote:  
 
 


Addressed for all files using breeding code in commit e823223. NC is currently treated the same as O, F, and the empty string.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
