### ISSUE TITLE
add fresh example data files

### ISSUE THREAD

**Issue by nmanich** [ngwalton/wbba_tools#5]
I will send you WBBA I data soon

**Comment by ngwalton** [comment]
Sample data were updated in commit 6125b016130936bbd1c127f69c3a1419d7d7acdb. The new sample files are named ebird_data_sample_wbbai.txt and ebird_data_sample_wbbaii.txt. There were a handful of records that were not matched (i.e. there are fewer records in the updated sample data files), but I assumed these were records that were excluded by users or review.
